{
    "original_file_metadata": {
        "file_name": "LFI/LFI.py",
        "CWEs": [
            20
        ],
        "kind": "fail",
        "region": {
            "start_line": 18,
            "end_line": null,
            "start_column": null,
            "end_column": null
        }
    },
    "mutated_file_metadata": {
        "used_templates": [
            {
                "template_file": "templates-db/languages/python/sensitivity/exceptions/tryCatchFinally.tmt",
                "template_name": "try_multi_cath_positive"
            }
        ],
        "used_extensions": [
            " EXPR_bool -> ~[EXPR_str]~.endswith(~[EXPR_str]~)",
            "EXPR_str -> ~[EXPR_str]~.strip()",
            "EXPR_str -> \"\"",
            "EXPR_str -> ~[EXPR_str]~.replace(~[EXPR_str]~, ~[EXPR_str]~)"
        ],
        "region": {
            "start_line": 40,
            "end_line": null,
            "start_column": null,
            "end_column": null
        }
    },
    "tool_results": [
        {
            "tool_name": "Analyzer3",
            "original_found_CWEs": [
                20,
                22
            ],
            "mutated_found_CWEs": []
        },
        {
            "tool_name": "Analyzer1",
            "original_found_CWEs": [
                20,
                22
            ],
            "mutated_found_CWEs": [
                563
            ]
        },
        {
            "tool_name": "Analyzer2",
            "original_found_CWEs": [
                20,
                22
            ],
            "mutated_found_CWEs": [
                668
            ]
        }
    ]
}